
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fddaf.c da2f.c dacornf.c daf.c dainterpf.c dagetarrayf.c dacreatef.c dalocalf.c dadistf.c dagtolf.c daindexf.c dagtonaf.c daltolf.c gr1f.c daghostf.c
OBJSC    = fddaf.o da2f.o dacornf.o daf.o dainterpf.o dagetarrayf.o dacreatef.o dalocalf.o dadistf.o dagtolf.o daindexf.o dagtonaf.o daltolf.o gr1f.o daghostf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscdm
LOCDIR   = src/dm/impls/da/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
