
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = daddf.c dadistf.c daf.c fddaf.c daindexf.c daltolf.c dacornf.c dageometryf.c dagtonaf.c dagetarrayf.c daghostf.c gr1f.c dagtolf.c dacreatef.c dainterpf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscdm
LOCDIR   = src/dm/impls/da/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
