#if !defined(__PETSCVERSION_H)
#define __PETSCVERSION_H

#define PETSC_VERSION_RELEASE    1
#define PETSC_VERSION_MAJOR      3
#define PETSC_VERSION_MINOR      2
#define PETSC_VERSION_SUBMINOR   0
#define PETSC_VERSION_PATCH      5
#define PETSC_VERSION_DATE       "Sep, 8, 2011"
#define PETSC_VERSION_PATCH_DATE "Sat Oct 29 13:45:54 CDT 2011"

#if !defined (PETSC_VERSION_HG)
#define PETSC_VERSION_HG         "bab12a7d073a6c7983421e06bc3095dbed94e6d4"
#endif

#if !defined(PETSC_VERSION_DATE_HG)
#define PETSC_VERSION_DATE_HG         "Sat Oct 29 13:41:37 2011 -0500"
#endif

#define PETSC_VERSION_(MAJOR,MINOR,SUBMINOR) \
  ((PETSC_VERSION_MAJOR == (MAJOR)) &&       \
   (PETSC_VERSION_MINOR == (MINOR)) &&       \
   (PETSC_VERSION_SUBMINOR == (SUBMINOR)) && \
   (PETSC_VERSION_RELEASE  == 1))

#endif
